# Generated by Django 6.0.6 on 2026-06-29 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_lecture_task_test_testquestion_testsubmission'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='examples',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lecture',
            name='explanation',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='lecture',
            name='key_points',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='lecture',
            name='topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lecture', to='notes.topic'),
        ),
        migrations.AddField(
            model_name='note',
            name='difficulty',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='note',
            name='learning_plan',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='task',
            name='estimated_time',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='task',
            name='locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='task',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(default='study', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='notes.topic'),
        ),
        migrations.AddField(
            model_name='test',
            name='topic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test', to='notes.topic'),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='correct_answer',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='testquestion',
            name='question_type',
            field=models.CharField(default='short_answer', max_length=50),
        ),
        migrations.AddField(
            model_name='topic',
            name='lecture_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='locked',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='order',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='topic',
            name='test_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='notes.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_history', to='users.user')),
            ],
        ),
        migrations.CreateModel(
            name='Progress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lecture_completed', models.BooleanField(default=False)),
                ('test_completed', models.BooleanField(default=False)),
                ('unlocked', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='notes.note')),
                ('topic', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='notes.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='users.user')),
            ],
            options={
                'unique_together': {('user', 'topic')},
            },
        ),
    ]
