# Generated by Django 6.0.6 on 2026-06-29 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_lecture_examples_lecture_explanation_and_more'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='note',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='note',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('locked', 'Locked'), ('unlocked', 'Unlocked'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='locked', max_length=50),
        ),
        migrations.AddField(
            model_name='task',
            name='study_time_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='test',
            name='passing_score',
            field=models.PositiveIntegerField(default=70),
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='correct_answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='strong_topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='weak_topics',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='testsubmission',
            name='wrong_answers',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='topic',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='topic',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='LearningProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tasks', models.PositiveIntegerField(default=0)),
                ('completed_tasks', models.PositiveIntegerField(default=0)),
                ('total_lectures', models.PositiveIntegerField(default=0)),
                ('completed_lectures', models.PositiveIntegerField(default=0)),
                ('total_tests', models.PositiveIntegerField(default=0)),
                ('completed_tests', models.PositiveIntegerField(default=0)),
                ('average_score', models.FloatField(default=0)),
                ('accuracy', models.FloatField(default=0)),
                ('completion_percentage', models.FloatField(default=0)),
                ('current_topic', models.CharField(blank=True, max_length=255)),
                ('current_module', models.CharField(blank=True, max_length=255)),
                ('study_time_seconds', models.PositiveIntegerField(default=0)),
                ('weak_topics', models.JSONField(blank=True, default=list)),
                ('strong_topics', models.JSONField(blank=True, default=list)),
                ('completed_modules', models.PositiveIntegerField(default=0)),
                ('completed_topics', models.PositiveIntegerField(default=0)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='notes.note')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_progress', to='users.user')),
            ],
            options={
                'unique_together': {('user', 'note')},
            },
        ),
    ]
