# Generated by Codex on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0004_module_completed_module_completed_at_note_completed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lecture",
            name="common_mistakes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lecture",
            name="detailed_explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lecture",
            name="exam_oriented_examples",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lecture",
            name="important_definitions",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lecture",
            name="introduction",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="lecture",
            name="quick_recap",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lecture",
            name="real_life_examples",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="lecture",
            name="revision_notes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="difficulty",
            field=models.CharField(default="Medium", max_length=50),
        ),
        migrations.AddField(
            model_name="testquestion",
            name="explanation",
            field=models.TextField(blank=True),
        ),
    ]
